[build]
  command = "npm install && npm run build"
  publish = "build"

# Primary redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicit redirects for SEO
[[redirects]]
  from = "/3d-printing"
  to = "/3d-printing-tashkent"
  status = 301
  force = true

[[redirects]]
  from = "/3d-printing-services"
  to = "/3d-printing-tashkent"
  status = 301
  force = true

[[redirects]]
  from = "/mould"
  to = "/injection-molding"
  status = 301
  force = true

[[redirects]]
  from = "/3d-scanning-services"
  to = "/3d-scanning"
  status = 301
  force = true

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "upgrade-insecure-requests"

# Special headers for SEO optimization
[[headers]]
  for = "/injection-molding"
  [headers.values]
    X-Robots-Tag = "all"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/3d-printing-tashkent"
  [headers.values]
    X-Robots-Tag = "all"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/digital-fabrication"
  [headers.values]
    X-Robots-Tag = "all"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/courses"
  [headers.values]
    X-Robots-Tag = "all"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/3d-scanning"
  [headers.values]
    X-Robots-Tag = "all"
    Access-Control-Allow-Origin = "*" 